export const DETAILED_CATEGORIES = [
  // Almacen
  "Aceites y Vinagres",
  "Aceites Comunes",
  "Aceites Especiales",
  "Acetos",
  "Jugos de Limón",
  "Vinagres",
  "Aderezos",
  "Mayonesas",
  "Ketchup",
  "Mostazas",
  "Salsas Golf",
  "Salsas Frías",
  "Otros Condimentos",
  "Arroz y Legumbres",
  "Arroz",
  "Arroz Listos",
  "Legumbres",
  "Sal, Pimienta y Especias",
  "Sal",
  "Especias",
  "Conservas",
  "Conservas de Carne",
  "Conservas de Frutas",
  "Conservas de Pescado",
  "Conservas de Verduras y Legumbres",
  "Desayuno y Merienda",
  "Azúcar y Edulcorantes",
  "Bizcochuelos, Budines y Magdalenas",
  "Cacao y Saborizantes",
  "Conservas de Verduras y Legumbres",
  "Cereales",
  "Galletitas Dulces",
  "Galletitas Saladas",
  "Leches",
  "Mermeladas y Jaleas",
  "Piononos",
  "Tés",
  "Yerbas",
  "Cafés",
  "Golosinas y Chocolates",
  "Alfajores",
  "Bocaditos y Postres",
  "Bombones",
  "Caramelos y Chicles",
  "Chocolates",
  "Turrones y Grageas",
  "Harinas",
  "Harinas",
  "Avenas y Sémolas",
  "Panificados",
  "Lacteados",
  "Pan Para Hamburguesas y Panchos",
  "Tostadas y Grisines",
  "Pan Rallado y Rebozador",
  "Integral y Salvado",
  "Sopas, Caldos y Puré",
  "Puré",
  "Sopas",
  "Caldos",
  "Para Preparar",
  "Bizcochuelos, Brownies y Tortas",
  "Comidas",
  "Flanes",
  "Gelatinas",
  "Helados",
  "Mousse",
  "Pastelería",
  "Postres",
  "Pastas Secas y Salsas",
  "Pastas Secas Guiseras",
  "Pastas Secas Largas",
  "Pastas Listas",
  "Salsas",
  "Snacks",
  "Frutas Secas y Disecadas",
  "Maní",
  "Nachos",
  "Palitos de Maíz",
  "Palitos Salados",
  "Papas Fritas",
  "Pochoclos",
  "Snacks",
  // Bebidas
  "A Base de Hierbas",
  "Aguas",
  "Aguas Sin Gas",
  "Aguas Con Gas",
  "Aguas Saborizadas",
  "Aperitivos",
  "Bebidas Blancas",
  "Cervezas",
  "Champagnes",
  "Energizantes",
  "Gaseosas",
  "Cola",
  "Lima Limón",
  "Naranja",
  "Pomelo",
  "Tónica",
  "Guaraná",
  "Generosos",
  "Hielo",
  "Isotónicas",
  "Jugos",
  "En Polvo",
  "Listos",
  "Granadina",
  "Frescos",
  "Licores",
  "Sidras",
  "Vinos",
  "Vinos Blancos",
  "Vinos Tintos",
  "Vinos Rosados",
  "Vinos Frizantes",
  "Whiskys",

  // Frutas
  "Frutas y Verduras",
  "Frutas",
  "Verduras",
  "Frutas Empaquetadas",
  "Frutas Secas y Desecadas",
  "Frutas Sueltas",
  "Frutas Congeladas",
  "Hierbas Aromáticas y Plantines",
  "Huevos",
  "Legumbres, Granos y Semillas",
  "Orgánicos",
  "Verduras",
  "Hortalizas Livianas",
  "Hortalizas Pesadas",
  "Verduras Empaquetadas",
  "Verduras Frescas de Hoja",
  "Verduras Procesadas y Ensaladas Listas",
  "Verduras Secas y Desecadas",

  // Lacteos
  "Cremas",
  "Dulce de Leche",
  "Leches",
  "Leches Larga Vida",
  "Leches Refrigeradas",
  "Leches Saborizadas",
  "Bebidas Vegetales",
  "Mantecas y Margarinas",
  "Manteca",
  "Margarinas",
  "Pastas y Tapas",
  "Fideos y Ñoquis",
  "Grasas",
  "Masas y Levaduras",
  "Pastas Rellenas",
  "Tapas",
  "Postres",
  "Yogures",
  "Yogures Descremados",
  "Yogures Enteros",

  // Perfumeria
  "Perfumería",
  "Cuidado Capilar",
  "Coloración",
  "Acondicionador",
  "Fijación",
  "Pediculosis",
  "Reparación y Tratamientos",
  "Shampoo",
  "Cepillos para Pelo",
  "Cuidado de la Piel",
  "Cremas Corporales",
  "Cremas Desmaquillantes",
  "Cremas Faciales",
  "Solares y Post-Solares",
  "Cuidado Personal",
  "Cepillos y Esponjas",
  "Depilación",
  "Desodorantes de Hombres",
  "Desodorantes de Mujer",
  "Desodorantes y Polvos Pédicos",
  "Geles de Ducha",
  "Jabones",
  "Protección Adultos",
  "Protección Femenina",
  "Productos Para Afeitarse",
  "Quitaesmaltes",
  "Higiene Preventiva",
  "Cuidado Oral",
  "Pastas Dentales",
  "Cepillos Dentales",
  "Enjuagues Bucales",
  "Accesorios Dentales",
  "Farmacia",
  "Algodón",
  "Alcohol",
  "Apósitos",
  "Preservativos",
  "Otros Farmacia",

  // Limpieza
  "Limpieza",
  "Accesorios de Limpieza",
  "Baldes y Mopas",
  "Bolsas",
  "Broches y Ganchos",
  "Escobas y Escobillones",
  "Escobillas",
  "Esponjas y Guantes",
  "Palas y Cabos",
  "Paños Multiusos",
  "Secadores y Cepillos",
  "Trapos de Piso",
  "Calzado",
  "Brillos y Revividores",
  "Limpiadores",
  "Pomadas Para Calzado",
  "Desodorantes de Ambiente",
  "Absorbe Humedad",
  "Aromatizantes",
  "Desodorantes y Desinfectantes",
  "Insecticidas",
  "Aerosoles",
  "Aparatos",
  "Cebos, Bolillas y Pastillas",
  "Escobas y Escobillones",
  "Tabletas y Difusores",
  "Repelentes",
  "Lavandina",
  "Limpieza de Baño",
  "Desinfectantes",
  "Destapa Cañerías",
  "Pastillas y Bloques",
  "Cuidado Para La Ropa",
  "Aprestos y Blanqueadores",
  "Cepillo Para Ropa",
  "Jabón en Pan",
  "Detergente Para Ropa",
  "Quitamanchas",
  "Suavizantes",
  "Perfumantes",
  "Limpieza de Cocina",
  "Detergentes",
  "Escarbadientes",
  "Fósforos",
  "Limpiadores",
  "Limpiavidrios",
  "Productos Para Lavavajillas",
  "Limpieza de Pisos y Muebles",
  "Ceras y Autobrillos",
  "Limpiadores de Pisos",
  "Lustramuebles",
  "Papeles",
  "Pañuelos",
  "Papel Higiénico",
  "Rollos de Cocina",
  "Servilletas",

  // Quesos y fiambres
  "Quesos y Fiambres",
  "Quesos",
  "Quesos Untables",
  "Queso Muzzarella",
  "Quesos Port Salut y Cremosos",
  "Quesos Semiblandos",
  "Quesos Duros",
  "Quesos Especiales e Importados",
  "Quesos Rallados",
  "Ricota",
  "Fiambres",
  "Jamón Cocido y Crudo",
  "Otros fiambres",
  "Dulces",
  "Encurtidos, Aceitunas y Pickles",
  "Salchichas",

  // Congelados
  "Congelados",
  "Comidas Congeladas",
  "Pizzas",
  "Empanadas y Tartas",
  "Comidas Congeladas",
  "Frutas",
  "Hamburguesas y Milanesas",
  "Helados y Postres",
  "Papas",
  "Pescados y Mariscos",
  "Pollo y Carnes",
  "Vegetales",

  // Pastas frescas
  "Pastas",
  "Pastas Simples",
  "Pastas Rellenas",
  "Salsa y Quesos",

  // Panadería y Pastelería
  "Panadería y Pastelería",
  "Panadería Salada",
  "Panificados",
  "Pizzas y Focaccias",
  "Sandwiches de Miga",
  "Panadería Dulce",
  "Pastelería",

  // Mascotas
  "Mascotas",
  "Accesorios para Mascotas",
  "Gatos",
  "Secos",
  "Húmedos",
  "Perros",
  "Secos",
  "Húmedos",
];

// Get Categories from API
export async function getCategories() {
  try {
    const response = await fetch(process.env.AHORRAPP_CENTRAL_API, {
      headers: {
        Authorization: `Bearer ${process.env.AHORRAPP_CENTRAL_API_TOKEN}`,
      },
    });

    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }

    const data = await response.json();

    if (data.success === true && Array.isArray(data.data)) {
      return data.data;
    } else {
      console.warn("API response unsuccessful, using fallback categories");
      return DETAILED_CATEGORIES;
    }
  } catch (error) {
    console.error("Error fetching categories from API:", error.message);
    return DETAILED_CATEGORIES;
  }
}

export const productEans = process.env.PRODUCT_EANS
  ? JSON.parse(process.env.PRODUCT_EANS)
  : [];
